version: "2"
services:
  php:
    image: diegomarangoni/hhvm
    ports:
      - "9000:9000"
    volumes:
      - ./../../DATA:/var/www/html #站点目录
      - ./php:/etc/hhvm #配置文件
    links:
      - mysql
      - redis
    command: "hhvm --mode=server" #初始调用
    container_name: hhvm


  nginx:
    image: hub.c.163.com/library/nginx:1.13.0-alpine
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./../../DATA:/var/www/html #站点目录
      - ./nginx/conf:/etc/nginx/conf.d #配置文件
    links:
      - php
      - redis
    container_name: nginx


  mysql:
    image: hub.c.163.com/library/mysql:latest
    ports: 
      - "3306:3306"
    volumes:
      - ./../../DATA/Mysql:/var/lib/mysql #持久化存储
      - ./mysql:/etc/mysql/conf.d #配置文件
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dell_456

      
  redis:
    image: hub.c.163.com/library/redis:3.2.6-alpine
    ports: 
      - "6379:6379"
    volumes:
      - ./../../DATA/Redis:/var/www/html/redis #持久化存储
      - ./redis:/usr/local/etc/redis #配置文件
    container_name: redis